<#ftl encoding="UTF-8"/>

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книги</title>
</head>
<body>
<div>
    <a href="profile">Профиль</a>

</div>
<div>

    <input id="log" type="text" placeholder="название книги" onkeyup="search();">

    <script>
        function search() {
            //отправка ajax запроса
        }

    </script>


</div>
</body>
</html>